2025-03-16 13:06:22.506 [info] (Client) Pylance async client (2025.3.2) started with python extension (2025.2.0)
2025-03-16 13:06:22.541 [info] [Info  - 1:06:22 PM] (8200) Server root directory: file:///c%3A/Users/Charl/.vscode/extensions/ms-python.vscode-pylance-2025.3.2/dist
2025-03-16 13:06:22.542 [info] [Info  - 1:06:22 PM] (8200) Pylance language server 2025.3.2 (pyright version 1.1.396, commit 3e2236a7) starting
2025-03-16 13:06:22.548 [info] [Info  - 1:06:22 PM] (8200) Starting service instance "getya proyecto"
2025-03-16 13:06:22.593 [info] [Info  - 1:06:22 PM] (8200) Setting environmentName for service "getya proyecto": "3.13.2 (global)"
2025-03-16 13:06:22.594 [info] [Info  - 1:06:22 PM] (8200) Setting pythonPath for service "getya proyecto": "C:\Users\Charl\AppData\Local\Programs\Python\Python313\python.exe"
2025-03-16 13:06:22.594 [info] [Info  - 1:06:22 PM] (8200) No include entries specified; assuming c:\Users\Charl\Desktop\getya proyecto
2025-03-16 13:06:22.596 [info] [Info  - 1:06:22 PM] (8200) Auto-excluding **/node_modules
2025-03-16 13:06:22.596 [info] [Info  - 1:06:22 PM] (8200) Auto-excluding **/__pycache__
2025-03-16 13:06:22.596 [info] [Info  - 1:06:22 PM] (8200) Auto-excluding **/.*
2025-03-16 13:06:22.932 [info] [Info  - 1:06:22 PM] (8200) Assuming Python version 3.13.2.final.0
2025-03-16 13:06:23.138 [info] [Info  - 1:06:23 PM] (8200) Found 1 source file
2025-03-16 13:06:23.507 [info] [Info  - 1:06:23 PM] (8200) Background analysis(1) root directory: file:///c%3A/Users/Charl/.vscode/extensions/ms-python.vscode-pylance-2025.3.2/dist
2025-03-16 13:06:23.509 [info] [Info  - 1:06:23 PM] (8200) Background analysis(1) started
2025-03-16 13:06:23.748 [info] [Info  - 1:06:23 PM] (8200) Indexer background runner(2) root directory: file:///c%3A/Users/Charl/.vscode/extensions/ms-python.vscode-pylance-2025.3.2/dist (index)
2025-03-16 13:06:23.748 [info] [Info  - 1:06:23 PM] (8200) Indexing(2) started
2025-03-16 13:06:24.709 [info] [Info  - 1:06:24 PM] (8200) scanned(2) 11 files over 1 exec env
2025-03-16 13:06:25.397 [info] [Info  - 1:06:25 PM] (8200) indexed(2) 11 files over 1 exec env
2025-03-16 13:06:25.407 [info] [Info  - 1:06:25 PM] (8200) Indexing finished(2).
2025-03-16 13:06:27.363 [info] [Info  - 1:06:27 PM] (8200) Starting service instance "<default>"
2025-03-16 13:06:27.393 [info] [Info  - 1:06:27 PM] (8200) Setting environmentName for service "<default>": "3.13.2 (global)"
2025-03-16 13:06:27.394 [info] [Info  - 1:06:27 PM] (8200) Setting pythonPath for service "<default>": "c:\Users\Charl\AppData\Local\Programs\Python\Python313\python.exe"
2025-03-16 13:06:27.394 [info] [Info  - 1:06:27 PM] (8200) No include entries specified; assuming \<default workspace root>
2025-03-16 13:06:27.394 [info] [Info  - 1:06:27 PM] (8200) Auto-excluding **/node_modules
2025-03-16 13:06:27.395 [info] [Info  - 1:06:27 PM] (8200) Auto-excluding **/__pycache__
2025-03-16 13:06:27.395 [info] [Info  - 1:06:27 PM] (8200) Auto-excluding **/.*
2025-03-16 13:06:27.447 [info] [Info  - 1:06:27 PM] (8200) Assuming Python version 3.13.2.final.0
2025-03-16 13:06:27.570 [info] [Error - 1:06:27 PM] (8200) File or directory "\<default workspace root>" does not exist.
2025-03-16 13:06:27.570 [info] [Info  - 1:06:27 PM] (8200) No source files found.
2025-03-16 13:06:27.938 [info] [Info  - 1:06:27 PM] (8200) Background analysis(3) root directory: file:///c%3A/Users/Charl/.vscode/extensions/ms-python.vscode-pylance-2025.3.2/dist
2025-03-16 13:06:27.940 [info] [Info  - 1:06:27 PM] (8200) Background analysis(3) started
2025-03-16 13:06:32.834 [info] [Info  - 1:06:32 PM] (8200) No source files found.
2025-03-16 13:07:44.086 [info] [Info  - 1:07:44 PM] (8200) Setting environmentName for service "getya proyecto": "3.13.2 (global)"
2025-03-16 13:07:44.086 [info] [Info  - 1:07:44 PM] (8200) Setting pythonPath for service "getya proyecto": "C:\Users\Charl\AppData\Local\Programs\Python\Python313\python.exe"
2025-03-16 13:07:44.086 [info] [Info  - 1:07:44 PM] (8200) No include entries specified; assuming c:\Users\Charl\Desktop\getya proyecto
2025-03-16 13:07:44.086 [info] [Info  - 1:07:44 PM] (8200) Auto-excluding **/node_modules
2025-03-16 13:07:44.086 [info] [Info  - 1:07:44 PM] (8200) Auto-excluding **/__pycache__
2025-03-16 13:07:44.087 [info] [Info  - 1:07:44 PM] (8200) Auto-excluding **/.*
2025-03-16 13:07:44.136 [info] [Info  - 1:07:44 PM] (8200) Assuming Python version 3.13.2.final.0
2025-03-16 13:07:44.262 [info] [Info  - 1:07:44 PM] (8200) No source files found.
2025-03-16 13:07:44.268 [info] [Info  - 1:07:44 PM] (8200) Setting environmentName for service "<default>": "3.13.2 (global)"
2025-03-16 13:07:44.269 [info] [Info  - 1:07:44 PM] (8200) Setting pythonPath for service "<default>": "c:\Users\Charl\AppData\Local\Programs\Python\Python313\python.exe"
2025-03-16 13:07:44.269 [info] [Info  - 1:07:44 PM] (8200) No include entries specified; assuming \<default workspace root>
2025-03-16 13:07:44.269 [info] [Info  - 1:07:44 PM] (8200) Auto-excluding **/node_modules
2025-03-16 13:07:44.269 [info] [Info  - 1:07:44 PM] (8200) Auto-excluding **/__pycache__
2025-03-16 13:07:44.269 [info] [Info  - 1:07:44 PM] (8200) Auto-excluding **/.*
2025-03-16 13:07:44.323 [info] [Info  - 1:07:44 PM] (8200) Assuming Python version 3.13.2.final.0
2025-03-16 13:07:44.441 [info] [Error - 1:07:44 PM] (8200) File or directory "\<default workspace root>" does not exist.
2025-03-16 13:07:44.441 [info] [Info  - 1:07:44 PM] (8200) No source files found.
2025-03-16 13:08:10.941 [info] [Info  - 1:08:10 PM] (8200) Found 1 source file
2025-03-16 13:08:10.976 [info] [Info  - 1:08:10 PM] (8200) Indexer background runner(4) root directory: file:///c%3A/Users/Charl/.vscode/extensions/ms-python.vscode-pylance-2025.3.2/dist (index)
2025-03-16 13:08:10.976 [info] [Info  - 1:08:10 PM] (8200) Indexing(4) started
2025-03-16 13:08:11.265 [info] [Info  - 1:08:11 PM] (8200) scanned(4) 11 files over 1 exec env
2025-03-16 13:08:11.393 [info] [Info  - 1:08:11 PM] (8200) indexed(4) 11 files over 1 exec env
2025-03-16 13:08:11.404 [info] [Info  - 1:08:11 PM] (8200) Indexing finished(4).
2025-03-16 13:08:39.370 [info] [Info  - 1:08:39 PM] (8200) No source files found.
2025-03-16 13:10:00.267 [info] [Info  - 1:10:00 PM] (8200) Setting environmentName for service "getya proyecto": "3.13.2 (global)"
2025-03-16 13:10:00.268 [info] [Info  - 1:10:00 PM] (8200) Setting pythonPath for service "getya proyecto": "C:\Users\Charl\AppData\Local\Programs\Python\Python313\python.exe"
2025-03-16 13:10:00.268 [info] [Info  - 1:10:00 PM] (8200) No include entries specified; assuming c:\Users\Charl\Desktop\getya proyecto
2025-03-16 13:10:00.268 [info] [Info  - 1:10:00 PM] (8200) Auto-excluding **/node_modules
2025-03-16 13:10:00.268 [info] [Info  - 1:10:00 PM] (8200) Auto-excluding **/__pycache__
2025-03-16 13:10:00.268 [info] [Info  - 1:10:00 PM] (8200) Auto-excluding **/.*
2025-03-16 13:10:00.317 [info] [Info  - 1:10:00 PM] (8200) Assuming Python version 3.13.2.final.0
2025-03-16 13:10:00.450 [info] [Info  - 1:10:00 PM] (8200) No source files found.
2025-03-16 13:10:00.455 [info] [Info  - 1:10:00 PM] (8200) Setting environmentName for service "<default>": "3.13.2 (global)"
2025-03-16 13:10:00.456 [info] [Info  - 1:10:00 PM] (8200) Setting pythonPath for service "<default>": "c:\Users\Charl\AppData\Local\Programs\Python\Python313\python.exe"
2025-03-16 13:10:00.456 [info] [Info  - 1:10:00 PM] (8200) No include entries specified; assuming \<default workspace root>
2025-03-16 13:10:00.456 [info] [Info  - 1:10:00 PM] (8200) Auto-excluding **/node_modules
2025-03-16 13:10:00.456 [info] [Info  - 1:10:00 PM] (8200) Auto-excluding **/__pycache__
2025-03-16 13:10:00.456 [info] [Info  - 1:10:00 PM] (8200) Auto-excluding **/.*
2025-03-16 13:10:00.524 [info] [Info  - 1:10:00 PM] (8200) Assuming Python version 3.13.2.final.0
2025-03-16 13:10:00.643 [info] [Error - 1:10:00 PM] (8200) File or directory "\<default workspace root>" does not exist.
2025-03-16 13:10:00.643 [info] [Info  - 1:10:00 PM] (8200) No source files found.
2025-03-16 13:10:06.885 [info] [Info  - 1:10:06 PM] (8200) Setting environmentName for service "getya proyecto": "3.13.2 (global)"
2025-03-16 13:10:06.885 [info] [Info  - 1:10:06 PM] (8200) Setting pythonPath for service "getya proyecto": "C:\Users\Charl\AppData\Local\Programs\Python\Python313\python.exe"
2025-03-16 13:10:06.885 [info] [Info  - 1:10:06 PM] (8200) No include entries specified; assuming c:\Users\Charl\Desktop\getya proyecto
2025-03-16 13:10:06.885 [info] [Info  - 1:10:06 PM] (8200) Auto-excluding **/node_modules
2025-03-16 13:10:06.885 [info] [Info  - 1:10:06 PM] (8200) Auto-excluding **/__pycache__
2025-03-16 13:10:06.885 [info] [Info  - 1:10:06 PM] (8200) Auto-excluding **/.*
2025-03-16 13:10:06.936 [info] [Info  - 1:10:06 PM] (8200) Assuming Python version 3.13.2.final.0
2025-03-16 13:10:07.067 [info] [Info  - 1:10:07 PM] (8200) No source files found.
2025-03-16 13:10:07.071 [info] [Info  - 1:10:07 PM] (8200) Setting environmentName for service "<default>": "3.13.2 (global)"
2025-03-16 13:10:07.071 [info] [Info  - 1:10:07 PM] (8200) Setting pythonPath for service "<default>": "c:\Users\Charl\AppData\Local\Programs\Python\Python313\python.exe"
2025-03-16 13:10:07.071 [info] [Info  - 1:10:07 PM] (8200) No include entries specified; assuming \<default workspace root>
2025-03-16 13:10:07.071 [info] [Info  - 1:10:07 PM] (8200) Auto-excluding **/node_modules
2025-03-16 13:10:07.071 [info] [Info  - 1:10:07 PM] (8200) Auto-excluding **/__pycache__
2025-03-16 13:10:07.071 [info] [Info  - 1:10:07 PM] (8200) Auto-excluding **/.*
2025-03-16 13:10:07.123 [info] [Info  - 1:10:07 PM] (8200) Assuming Python version 3.13.2.final.0
2025-03-16 13:10:07.247 [info] [Error - 1:10:07 PM] (8200) File or directory "\<default workspace root>" does not exist.
2025-03-16 13:10:07.247 [info] [Info  - 1:10:07 PM] (8200) No source files found.
2025-03-16 13:10:10.504 [info] [Info  - 1:10:10 PM] (8200) Setting environmentName for service "getya proyecto": "3.13.2 (global)"
2025-03-16 13:10:10.505 [info] [Info  - 1:10:10 PM] (8200) Setting pythonPath for service "getya proyecto": "C:\Users\Charl\AppData\Local\Programs\Python\Python313\python.exe"
2025-03-16 13:10:10.505 [info] [Info  - 1:10:10 PM] (8200) No include entries specified; assuming c:\Users\Charl\Desktop\getya proyecto
2025-03-16 13:10:10.505 [info] [Info  - 1:10:10 PM] (8200) Auto-excluding **/node_modules
2025-03-16 13:10:10.505 [info] [Info  - 1:10:10 PM] (8200) Auto-excluding **/__pycache__
2025-03-16 13:10:10.505 [info] [Info  - 1:10:10 PM] (8200) Auto-excluding **/.*
2025-03-16 13:10:10.563 [info] [Info  - 1:10:10 PM] (8200) Assuming Python version 3.13.2.final.0
2025-03-16 13:10:10.692 [info] [Info  - 1:10:10 PM] (8200) No source files found.
2025-03-16 13:10:10.696 [info] [Info  - 1:10:10 PM] (8200) Setting environmentName for service "<default>": "3.13.2 (global)"
2025-03-16 13:10:10.698 [info] [Info  - 1:10:10 PM] (8200) Setting pythonPath for service "<default>": "c:\Users\Charl\AppData\Local\Programs\Python\Python313\python.exe"
2025-03-16 13:10:10.698 [info] [Info  - 1:10:10 PM] (8200) No include entries specified; assuming \<default workspace root>
2025-03-16 13:10:10.698 [info] [Info  - 1:10:10 PM] (8200) Auto-excluding **/node_modules
2025-03-16 13:10:10.698 [info] [Info  - 1:10:10 PM] (8200) Auto-excluding **/__pycache__
2025-03-16 13:10:10.698 [info] [Info  - 1:10:10 PM] (8200) Auto-excluding **/.*
2025-03-16 13:10:10.771 [info] [Info  - 1:10:10 PM] (8200) Assuming Python version 3.13.2.final.0
2025-03-16 13:10:10.891 [info] [Error - 1:10:10 PM] (8200) File or directory "\<default workspace root>" does not exist.
2025-03-16 13:10:10.891 [info] [Info  - 1:10:10 PM] (8200) No source files found.
2025-03-16 13:10:14.395 [info] [Info  - 1:10:14 PM] (8200) Setting environmentName for service "getya proyecto": "3.13.2 (global)"
2025-03-16 13:10:14.396 [info] [Info  - 1:10:14 PM] (8200) Setting pythonPath for service "getya proyecto": "C:\Users\Charl\AppData\Local\Programs\Python\Python313\python.exe"
2025-03-16 13:10:14.396 [info] [Info  - 1:10:14 PM] (8200) No include entries specified; assuming c:\Users\Charl\Desktop\getya proyecto
2025-03-16 13:10:14.396 [info] [Info  - 1:10:14 PM] (8200) Auto-excluding **/node_modules
2025-03-16 13:10:14.396 [info] [Info  - 1:10:14 PM] (8200) Auto-excluding **/__pycache__
2025-03-16 13:10:14.396 [info] [Info  - 1:10:14 PM] (8200) Auto-excluding **/.*
2025-03-16 13:10:14.448 [info] [Info  - 1:10:14 PM] (8200) Assuming Python version 3.13.2.final.0
2025-03-16 13:10:14.579 [info] [Info  - 1:10:14 PM] (8200) No source files found.
2025-03-16 13:10:14.583 [info] [Info  - 1:10:14 PM] (8200) Setting environmentName for service "<default>": "3.13.2 (global)"
2025-03-16 13:10:14.583 [info] [Info  - 1:10:14 PM] (8200) Setting pythonPath for service "<default>": "c:\Users\Charl\AppData\Local\Programs\Python\Python313\python.exe"
2025-03-16 13:10:14.583 [info] [Info  - 1:10:14 PM] (8200) No include entries specified; assuming \<default workspace root>
2025-03-16 13:10:14.584 [info] [Info  - 1:10:14 PM] (8200) Auto-excluding **/node_modules
2025-03-16 13:10:14.584 [info] [Info  - 1:10:14 PM] (8200) Auto-excluding **/__pycache__
2025-03-16 13:10:14.584 [info] [Info  - 1:10:14 PM] (8200) Auto-excluding **/.*
2025-03-16 13:10:14.639 [info] [Info  - 1:10:14 PM] (8200) Assuming Python version 3.13.2.final.0
2025-03-16 13:10:14.767 [info] [Error - 1:10:14 PM] (8200) File or directory "\<default workspace root>" does not exist.
2025-03-16 13:10:14.768 [info] [Info  - 1:10:14 PM] (8200) No source files found.
2025-03-16 13:10:18.682 [info] [Info  - 1:10:18 PM] (8200) Setting environmentName for service "getya proyecto": "3.13.2 (global)"
2025-03-16 13:10:18.682 [info] [Info  - 1:10:18 PM] (8200) Setting pythonPath for service "getya proyecto": "C:\Users\Charl\AppData\Local\Programs\Python\Python313\python.exe"
2025-03-16 13:10:18.682 [info] [Info  - 1:10:18 PM] (8200) No include entries specified; assuming c:\Users\Charl\Desktop\getya proyecto
2025-03-16 13:10:18.682 [info] [Info  - 1:10:18 PM] (8200) Auto-excluding **/node_modules
2025-03-16 13:10:18.682 [info] [Info  - 1:10:18 PM] (8200) Auto-excluding **/__pycache__
2025-03-16 13:10:18.683 [info] [Info  - 1:10:18 PM] (8200) Auto-excluding **/.*
2025-03-16 13:10:18.739 [info] [Info  - 1:10:18 PM] (8200) Assuming Python version 3.13.2.final.0
2025-03-16 13:10:18.868 [info] [Info  - 1:10:18 PM] (8200) No source files found.
2025-03-16 13:10:18.872 [info] [Info  - 1:10:18 PM] (8200) Setting environmentName for service "<default>": "3.13.2 (global)"
2025-03-16 13:10:18.872 [info] [Info  - 1:10:18 PM] (8200) Setting pythonPath for service "<default>": "c:\Users\Charl\AppData\Local\Programs\Python\Python313\python.exe"
2025-03-16 13:10:18.873 [info] [Info  - 1:10:18 PM] (8200) No include entries specified; assuming \<default workspace root>
2025-03-16 13:10:18.873 [info] [Info  - 1:10:18 PM] (8200) Auto-excluding **/node_modules
2025-03-16 13:10:18.873 [info] [Info  - 1:10:18 PM] (8200) Auto-excluding **/__pycache__
2025-03-16 13:10:18.873 [info] [Info  - 1:10:18 PM] (8200) Auto-excluding **/.*
2025-03-16 13:10:18.932 [info] [Info  - 1:10:18 PM] (8200) Assuming Python version 3.13.2.final.0
2025-03-16 13:10:19.053 [info] [Error - 1:10:19 PM] (8200) File or directory "\<default workspace root>" does not exist.
2025-03-16 13:10:19.053 [info] [Info  - 1:10:19 PM] (8200) No source files found.
2025-03-16 13:10:22.426 [info] [Info  - 1:10:22 PM] (8200) Setting environmentName for service "getya proyecto": "3.13.2 (global)"
2025-03-16 13:10:22.426 [info] [Info  - 1:10:22 PM] (8200) Setting pythonPath for service "getya proyecto": "C:\Users\Charl\AppData\Local\Programs\Python\Python313\python.exe"
2025-03-16 13:10:22.427 [info] [Info  - 1:10:22 PM] (8200) No include entries specified; assuming c:\Users\Charl\Desktop\getya proyecto
2025-03-16 13:10:22.427 [info] [Info  - 1:10:22 PM] (8200) Auto-excluding **/node_modules
2025-03-16 13:10:22.427 [info] [Info  - 1:10:22 PM] (8200) Auto-excluding **/__pycache__
2025-03-16 13:10:22.427 [info] [Info  - 1:10:22 PM] (8200) Auto-excluding **/.*
2025-03-16 13:10:22.477 [info] [Info  - 1:10:22 PM] (8200) Assuming Python version 3.13.2.final.0
2025-03-16 13:10:22.595 [info] [Info  - 1:10:22 PM] (8200) No source files found.
2025-03-16 13:10:22.600 [info] [Info  - 1:10:22 PM] (8200) Setting environmentName for service "<default>": "3.13.2 (global)"
2025-03-16 13:10:22.600 [info] [Info  - 1:10:22 PM] (8200) Setting pythonPath for service "<default>": "c:\Users\Charl\AppData\Local\Programs\Python\Python313\python.exe"
2025-03-16 13:10:22.601 [info] [Info  - 1:10:22 PM] (8200) No include entries specified; assuming \<default workspace root>
2025-03-16 13:10:22.601 [info] [Info  - 1:10:22 PM] (8200) Auto-excluding **/node_modules
2025-03-16 13:10:22.601 [info] [Info  - 1:10:22 PM] (8200) Auto-excluding **/__pycache__
2025-03-16 13:10:22.601 [info] [Info  - 1:10:22 PM] (8200) Auto-excluding **/.*
2025-03-16 13:10:22.666 [info] [Info  - 1:10:22 PM] (8200) Assuming Python version 3.13.2.final.0
2025-03-16 13:10:22.793 [info] [Error - 1:10:22 PM] (8200) File or directory "\<default workspace root>" does not exist.
2025-03-16 13:10:22.793 [info] [Info  - 1:10:22 PM] (8200) No source files found.
2025-03-16 13:10:26.644 [info] [Info  - 1:10:26 PM] (8200) Setting environmentName for service "getya proyecto": "3.13.2 (global)"
2025-03-16 13:10:26.644 [info] [Info  - 1:10:26 PM] (8200) Setting pythonPath for service "getya proyecto": "C:\Users\Charl\AppData\Local\Programs\Python\Python313\python.exe"
2025-03-16 13:10:26.644 [info] [Info  - 1:10:26 PM] (8200) No include entries specified; assuming c:\Users\Charl\Desktop\getya proyecto
2025-03-16 13:10:26.644 [info] [Info  - 1:10:26 PM] (8200) Auto-excluding **/node_modules
2025-03-16 13:10:26.645 [info] [Info  - 1:10:26 PM] (8200) Auto-excluding **/__pycache__
2025-03-16 13:10:26.645 [info] [Info  - 1:10:26 PM] (8200) Auto-excluding **/.*
2025-03-16 13:10:26.700 [info] [Info  - 1:10:26 PM] (8200) Assuming Python version 3.13.2.final.0
2025-03-16 13:10:26.832 [info] [Info  - 1:10:26 PM] (8200) No source files found.
2025-03-16 13:10:26.836 [info] [Info  - 1:10:26 PM] (8200) Setting environmentName for service "<default>": "3.13.2 (global)"
2025-03-16 13:10:26.836 [info] [Info  - 1:10:26 PM] (8200) Setting pythonPath for service "<default>": "c:\Users\Charl\AppData\Local\Programs\Python\Python313\python.exe"
2025-03-16 13:10:26.836 [info] [Info  - 1:10:26 PM] (8200) No include entries specified; assuming \<default workspace root>
2025-03-16 13:10:26.836 [info] [Info  - 1:10:26 PM] (8200) Auto-excluding **/node_modules
2025-03-16 13:10:26.836 [info] [Info  - 1:10:26 PM] (8200) Auto-excluding **/__pycache__
2025-03-16 13:10:26.837 [info] [Info  - 1:10:26 PM] (8200) Auto-excluding **/.*
2025-03-16 13:10:26.910 [info] [Info  - 1:10:26 PM] (8200) Assuming Python version 3.13.2.final.0
2025-03-16 13:10:27.029 [info] [Error - 1:10:27 PM] (8200) File or directory "\<default workspace root>" does not exist.
2025-03-16 13:10:27.029 [info] [Info  - 1:10:27 PM] (8200) No source files found.
2025-03-16 13:11:03.163 [info] [Info  - 1:11:03 PM] Server process exited successfully
2025-03-16 13:11:03.740 [info] (Client) Pylance async client (2025.3.2) started with python extension (2025.2.0)
2025-03-16 13:11:04.257 [info] [Info  - 1:11:04 PM] (11156) Server root directory: file:///c%3A/Users/Charl/.vscode/extensions/ms-python.vscode-pylance-2025.3.2/dist
2025-03-16 13:11:04.258 [info] [Info  - 1:11:04 PM] (11156) Pylance language server 2025.3.2 (pyright version 1.1.396, commit 3e2236a7) starting
2025-03-16 13:11:04.263 [info] [Info  - 1:11:04 PM] (11156) Starting service instance "getya proyecto"
2025-03-16 13:11:04.288 [info] [Info  - 1:11:04 PM] (11156) Setting environmentName for service "getya proyecto": "3.13.2 (global)"
2025-03-16 13:11:04.288 [info] [Info  - 1:11:04 PM] (11156) Setting pythonPath for service "getya proyecto": "C:\Users\Charl\AppData\Local\Programs\Python\Python313\python.exe"
2025-03-16 13:11:04.288 [info] [Info  - 1:11:04 PM] (11156) No include entries specified; assuming c:\Users\Charl\Desktop\getya proyecto
2025-03-16 13:11:04.288 [info] [Info  - 1:11:04 PM] (11156) Auto-excluding **/node_modules
2025-03-16 13:11:04.288 [info] [Info  - 1:11:04 PM] (11156) Auto-excluding **/__pycache__
2025-03-16 13:11:04.288 [info] [Info  - 1:11:04 PM] (11156) Auto-excluding **/.*
2025-03-16 13:11:04.342 [info] [Info  - 1:11:04 PM] (11156) Assuming Python version 3.13.2.final.0
2025-03-16 13:11:04.486 [info] [Info  - 1:11:04 PM] (11156) No source files found.
2025-03-16 13:11:04.829 [info] [Info  - 1:11:04 PM] (11156) Background analysis(1) root directory: file:///c%3A/Users/Charl/.vscode/extensions/ms-python.vscode-pylance-2025.3.2/dist
2025-03-16 13:11:04.831 [info] [Info  - 1:11:04 PM] (11156) Background analysis(1) started
2025-03-16 13:15:13.738 [info] (Client) Pylance async client (2025.3.2) started with python extension (2025.2.0)
2025-03-16 13:15:13.765 [info] [Info  - 1:15:13 PM] (18740) Server root directory: file:///c%3A/Users/Charl/.vscode/extensions/ms-python.vscode-pylance-2025.3.2/dist
2025-03-16 13:15:13.768 [info] [Info  - 1:15:13 PM] (18740) Pylance language server 2025.3.2 (pyright version 1.1.396, commit 3e2236a7) starting
2025-03-16 13:15:13.772 [info] [Info  - 1:15:13 PM] (18740) Starting service instance "getya proyecto"
2025-03-16 13:15:13.816 [info] [Info  - 1:15:13 PM] (18740) Setting environmentName for service "getya proyecto": "3.13.2 (global)"
2025-03-16 13:15:13.816 [info] [Info  - 1:15:13 PM] (18740) Setting pythonPath for service "getya proyecto": "C:\Users\Charl\AppData\Local\Programs\Python\Python313\python.exe"
2025-03-16 13:15:13.817 [info] [Info  - 1:15:13 PM] (18740) No include entries specified; assuming c:\Users\Charl\Desktop\getya proyecto
2025-03-16 13:15:13.817 [info] [Info  - 1:15:13 PM] (18740) Auto-excluding **/node_modules
2025-03-16 13:15:13.818 [info] [Info  - 1:15:13 PM] (18740) Auto-excluding **/__pycache__
2025-03-16 13:15:13.818 [info] [Info  - 1:15:13 PM] (18740) Auto-excluding **/.*
2025-03-16 13:15:13.891 [info] [Info  - 1:15:13 PM] (18740) Assuming Python version 3.13.2.final.0
2025-03-16 13:15:14.056 [info] [Info  - 1:15:14 PM] (18740) Found 1 source file
2025-03-16 13:15:14.527 [info] [Info  - 1:15:14 PM] (18740) Background analysis(1) root directory: file:///c%3A/Users/Charl/.vscode/extensions/ms-python.vscode-pylance-2025.3.2/dist
2025-03-16 13:15:14.529 [info] [Info  - 1:15:14 PM] (18740) Background analysis(1) started
2025-03-16 13:15:15.209 [info] [Info  - 1:15:15 PM] (18740) Indexer background runner(2) root directory: file:///c%3A/Users/Charl/.vscode/extensions/ms-python.vscode-pylance-2025.3.2/dist (index)
2025-03-16 13:15:15.209 [info] [Info  - 1:15:15 PM] (18740) Indexing(2) started
2025-03-16 13:15:15.593 [info] [Info  - 1:15:15 PM] (18740) scanned(2) 11 files over 1 exec env
2025-03-16 13:15:15.729 [info] [Info  - 1:15:15 PM] (18740) indexed(2) 11 files over 1 exec env
2025-03-16 13:15:15.740 [info] [Info  - 1:15:15 PM] (18740) Indexing finished(2).
2025-03-16 13:15:18.584 [info] [Info  - 1:15:18 PM] (18740) Starting service instance "<default>"
2025-03-16 13:15:18.601 [info] [Info  - 1:15:18 PM] (18740) Setting environmentName for service "<default>": "3.13.2 (global)"
2025-03-16 13:15:18.601 [info] [Info  - 1:15:18 PM] (18740) Setting pythonPath for service "<default>": "c:\Users\Charl\AppData\Local\Programs\Python\Python313\python.exe"
2025-03-16 13:15:18.601 [info] [Info  - 1:15:18 PM] (18740) No include entries specified; assuming \<default workspace root>
2025-03-16 13:15:18.602 [info] [Info  - 1:15:18 PM] (18740) Auto-excluding **/node_modules
2025-03-16 13:15:18.602 [info] [Info  - 1:15:18 PM] (18740) Auto-excluding **/__pycache__
2025-03-16 13:15:18.602 [info] [Info  - 1:15:18 PM] (18740) Auto-excluding **/.*
2025-03-16 13:15:18.652 [info] [Info  - 1:15:18 PM] (18740) Assuming Python version 3.13.2.final.0
2025-03-16 13:15:18.801 [info] [Error - 1:15:18 PM] (18740) File or directory "\<default workspace root>" does not exist.
2025-03-16 13:15:18.801 [info] [Info  - 1:15:18 PM] (18740) No source files found.
2025-03-16 13:15:19.165 [info] [Info  - 1:15:19 PM] (18740) Background analysis(3) root directory: file:///c%3A/Users/Charl/.vscode/extensions/ms-python.vscode-pylance-2025.3.2/dist
2025-03-16 13:15:19.167 [info] [Info  - 1:15:19 PM] (18740) Background analysis(3) started
2025-03-16 13:18:54.995 [info] [Info  - 1:18:54 PM] Server process exited successfully
2025-03-16 13:18:55.546 [info] (Client) Pylance async client (2025.3.2) started with python extension (2025.2.0)
2025-03-16 13:18:56.076 [info] [Info  - 1:18:56 PM] (5408) Server root directory: file:///c%3A/Users/Charl/.vscode/extensions/ms-python.vscode-pylance-2025.3.2/dist
2025-03-16 13:18:56.077 [info] [Info  - 1:18:56 PM] (5408) Pylance language server 2025.3.2 (pyright version 1.1.396, commit 3e2236a7) starting
2025-03-16 13:18:56.082 [info] [Info  - 1:18:56 PM] (5408) Starting service instance "getya proyecto"
2025-03-16 13:18:56.110 [info] [Info  - 1:18:56 PM] (5408) Setting environmentName for service "getya proyecto": "3.13.2 (global)"
2025-03-16 13:18:56.110 [info] [Info  - 1:18:56 PM] (5408) Setting pythonPath for service "getya proyecto": "C:\Users\Charl\AppData\Local\Programs\Python\Python313\python.exe"
2025-03-16 13:18:56.111 [info] [Info  - 1:18:56 PM] (5408) No include entries specified; assuming c:\Users\Charl\Desktop\getya proyecto
2025-03-16 13:18:56.111 [info] [Info  - 1:18:56 PM] (5408) Auto-excluding **/node_modules
2025-03-16 13:18:56.111 [info] [Info  - 1:18:56 PM] (5408) Auto-excluding **/__pycache__
2025-03-16 13:18:56.112 [info] [Info  - 1:18:56 PM] (5408) Auto-excluding **/.*
2025-03-16 13:18:56.166 [info] [Info  - 1:18:56 PM] (5408) Assuming Python version 3.13.2.final.0
2025-03-16 13:18:56.310 [info] [Info  - 1:18:56 PM] (5408) Found 1 source file
2025-03-16 13:18:56.669 [info] [Info  - 1:18:56 PM] (5408) Background analysis(1) root directory: file:///c%3A/Users/Charl/.vscode/extensions/ms-python.vscode-pylance-2025.3.2/dist
2025-03-16 13:18:56.671 [info] [Info  - 1:18:56 PM] (5408) Background analysis(1) started
2025-03-16 13:18:56.836 [info] [Info  - 1:18:56 PM] (5408) Indexer background runner(2) root directory: file:///c%3A/Users/Charl/.vscode/extensions/ms-python.vscode-pylance-2025.3.2/dist (index)
2025-03-16 13:18:56.837 [info] [Info  - 1:18:56 PM] (5408) Indexing(2) started
2025-03-16 13:18:57.585 [info] [Info  - 1:18:57 PM] (5408) scanned(2) 11 files over 1 exec env
2025-03-16 13:18:57.730 [info] [Info  - 1:18:57 PM] (5408) indexed(2) 11 files over 1 exec env
2025-03-16 13:18:57.740 [info] [Info  - 1:18:57 PM] (5408) Indexing finished(2).
2025-03-16 13:19:58.644 [info] [Info  - 1:19:58 PM] (5408) Setting environmentName for service "getya proyecto": "3.13.2 (global)"
2025-03-16 13:19:58.644 [info] [Info  - 1:19:58 PM] (5408) Setting pythonPath for service "getya proyecto": "C:\Users\Charl\AppData\Local\Programs\Python\Python313\python.exe"
2025-03-16 13:19:58.644 [info] [Info  - 1:19:58 PM] (5408) No include entries specified; assuming c:\Users\Charl\Desktop\getya proyecto
2025-03-16 13:19:58.644 [info] [Info  - 1:19:58 PM] (5408) Auto-excluding **/node_modules
2025-03-16 13:19:58.644 [info] [Info  - 1:19:58 PM] (5408) Auto-excluding **/__pycache__
2025-03-16 13:19:58.645 [info] [Info  - 1:19:58 PM] (5408) Auto-excluding **/.*
2025-03-16 13:19:58.706 [info] [Info  - 1:19:58 PM] (5408) Assuming Python version 3.13.2.final.0
2025-03-16 13:19:58.857 [info] [Info  - 1:19:58 PM] (5408) Found 1 source file
2025-03-16 13:19:59.387 [info] [Info  - 1:19:59 PM] (5408) Indexer background runner(3) root directory: file:///c%3A/Users/Charl/.vscode/extensions/ms-python.vscode-pylance-2025.3.2/dist (index)
2025-03-16 13:19:59.387 [info] [Info  - 1:19:59 PM] (5408) Indexing(3) started
2025-03-16 13:19:59.659 [info] [Info  - 1:19:59 PM] (5408) scanned(3) 11 files over 1 exec env
2025-03-16 13:19:59.780 [info] [Info  - 1:19:59 PM] (5408) indexed(3) 11 files over 1 exec env
2025-03-16 13:19:59.789 [info] [Info  - 1:19:59 PM] (5408) Indexing finished(3).
2025-03-16 13:22:54.052 [info] [Info  - 1:22:54 PM] Server process exited successfully
2025-03-16 13:22:54.606 [info] (Client) Pylance async client (2025.3.2) started with python extension (2025.2.0)
2025-03-16 13:22:55.133 [info] [Info  - 1:22:55 PM] (7520) Server root directory: file:///c%3A/Users/Charl/.vscode/extensions/ms-python.vscode-pylance-2025.3.2/dist
2025-03-16 13:22:55.134 [info] [Info  - 1:22:55 PM] (7520) Pylance language server 2025.3.2 (pyright version 1.1.396, commit 3e2236a7) starting
2025-03-16 13:22:55.139 [info] [Info  - 1:22:55 PM] (7520) Starting service instance "getya proyecto"
2025-03-16 13:22:55.166 [info] [Info  - 1:22:55 PM] (7520) Setting environmentName for service "getya proyecto": "3.13.2 (global)"
2025-03-16 13:22:55.166 [info] [Info  - 1:22:55 PM] (7520) Setting pythonPath for service "getya proyecto": "C:\Users\Charl\AppData\Local\Programs\Python\Python313\python.exe"
2025-03-16 13:22:55.167 [info] [Info  - 1:22:55 PM] (7520) No include entries specified; assuming c:\Users\Charl\Desktop\getya proyecto
2025-03-16 13:22:55.167 [info] [Info  - 1:22:55 PM] (7520) Auto-excluding **/node_modules
2025-03-16 13:22:55.168 [info] [Info  - 1:22:55 PM] (7520) Auto-excluding **/__pycache__
2025-03-16 13:22:55.168 [info] [Info  - 1:22:55 PM] (7520) Auto-excluding **/.*
2025-03-16 13:22:55.223 [info] [Info  - 1:22:55 PM] (7520) Assuming Python version 3.13.2.final.0
2025-03-16 13:22:55.384 [info] [Info  - 1:22:55 PM] (7520) Found 1 source file
2025-03-16 13:22:55.760 [info] [Info  - 1:22:55 PM] (7520) Background analysis(1) root directory: file:///c%3A/Users/Charl/.vscode/extensions/ms-python.vscode-pylance-2025.3.2/dist
2025-03-16 13:22:55.762 [info] [Info  - 1:22:55 PM] (7520) Background analysis(1) started
2025-03-16 13:22:55.933 [info] [Info  - 1:22:55 PM] (7520) Indexer background runner(2) root directory: file:///c%3A/Users/Charl/.vscode/extensions/ms-python.vscode-pylance-2025.3.2/dist (index)
2025-03-16 13:22:55.933 [info] [Info  - 1:22:55 PM] (7520) Indexing(2) started
2025-03-16 13:22:56.721 [info] [Info  - 1:22:56 PM] (7520) scanned(2) 11 files over 1 exec env
2025-03-16 13:22:56.860 [info] [Info  - 1:22:56 PM] (7520) indexed(2) 11 files over 1 exec env
2025-03-16 13:22:56.870 [info] [Info  - 1:22:56 PM] (7520) Indexing finished(2).
2025-03-16 13:23:17.021 [info] [Info  - 1:23:17 PM] Server process exited successfully
2025-03-16 13:23:17.565 [info] (Client) Pylance async client (2025.3.2) started with python extension (2025.2.0)
2025-03-16 13:23:18.078 [info] [Info  - 1:23:18 PM] (4464) Server root directory: file:///c%3A/Users/Charl/.vscode/extensions/ms-python.vscode-pylance-2025.3.2/dist
2025-03-16 13:23:18.081 [info] [Info  - 1:23:18 PM] (4464) Pylance language server 2025.3.2 (pyright version 1.1.396, commit 3e2236a7) starting
2025-03-16 13:23:18.085 [info] [Info  - 1:23:18 PM] (4464) Starting service instance "getya proyecto"
2025-03-16 13:23:18.110 [info] [Info  - 1:23:18 PM] (4464) Setting environmentName for service "getya proyecto": "3.13.2 (global)"
2025-03-16 13:23:18.111 [info] [Info  - 1:23:18 PM] (4464) Setting pythonPath for service "getya proyecto": "C:\Users\Charl\AppData\Local\Programs\Python\Python313\python.exe"
2025-03-16 13:23:18.111 [info] [Info  - 1:23:18 PM] (4464) No include entries specified; assuming c:\Users\Charl\Desktop\getya proyecto
2025-03-16 13:23:18.112 [info] [Info  - 1:23:18 PM] (4464) Auto-excluding **/node_modules
2025-03-16 13:23:18.112 [info] [Info  - 1:23:18 PM] (4464) Auto-excluding **/__pycache__
2025-03-16 13:23:18.112 [info] [Info  - 1:23:18 PM] (4464) Auto-excluding **/.*
2025-03-16 13:23:18.166 [info] [Info  - 1:23:18 PM] (4464) Assuming Python version 3.13.2.final.0
2025-03-16 13:23:18.312 [info] [Info  - 1:23:18 PM] (4464) Found 1 source file
2025-03-16 13:23:18.716 [info] [Info  - 1:23:18 PM] (4464) Background analysis(1) root directory: file:///c%3A/Users/Charl/.vscode/extensions/ms-python.vscode-pylance-2025.3.2/dist
2025-03-16 13:23:18.718 [info] [Info  - 1:23:18 PM] (4464) Background analysis(1) started
2025-03-16 13:23:18.881 [info] [Info  - 1:23:18 PM] (4464) Indexer background runner(2) root directory: file:///c%3A/Users/Charl/.vscode/extensions/ms-python.vscode-pylance-2025.3.2/dist (index)
2025-03-16 13:23:18.881 [info] [Info  - 1:23:18 PM] (4464) Indexing(2) started
2025-03-16 13:23:19.708 [info] [Info  - 1:23:19 PM] (4464) scanned(2) 11 files over 1 exec env
2025-03-16 13:23:19.859 [info] [Info  - 1:23:19 PM] (4464) indexed(2) 11 files over 1 exec env
2025-03-16 13:23:19.869 [info] [Info  - 1:23:19 PM] (4464) Indexing finished(2).
2025-03-16 13:23:32.139 [info] [Info  - 1:23:32 PM] Server process exited successfully
2025-03-16 13:23:32.689 [info] (Client) Pylance async client (2025.3.2) started with python extension (2025.2.0)
2025-03-16 13:23:33.210 [info] [Info  - 1:23:33 PM] (8392) Server root directory: file:///c%3A/Users/Charl/.vscode/extensions/ms-python.vscode-pylance-2025.3.2/dist
2025-03-16 13:23:33.212 [info] [Info  - 1:23:33 PM] (8392) Pylance language server 2025.3.2 (pyright version 1.1.396, commit 3e2236a7) starting
2025-03-16 13:23:33.216 [info] [Info  - 1:23:33 PM] (8392) Starting service instance "getya proyecto"
2025-03-16 13:23:33.242 [info] [Info  - 1:23:33 PM] (8392) Setting environmentName for service "getya proyecto": "3.13.2 (global)"
2025-03-16 13:23:33.242 [info] [Info  - 1:23:33 PM] (8392) Setting pythonPath for service "getya proyecto": "C:\Users\Charl\AppData\Local\Programs\Python\Python313\python.exe"
2025-03-16 13:23:33.243 [info] [Info  - 1:23:33 PM] (8392) No include entries specified; assuming c:\Users\Charl\Desktop\getya proyecto
2025-03-16 13:23:33.243 [info] [Info  - 1:23:33 PM] (8392) Auto-excluding **/node_modules
2025-03-16 13:23:33.243 [info] [Info  - 1:23:33 PM] (8392) Auto-excluding **/__pycache__
2025-03-16 13:23:33.244 [info] [Info  - 1:23:33 PM] (8392) Auto-excluding **/.*
2025-03-16 13:23:33.299 [info] [Info  - 1:23:33 PM] (8392) Assuming Python version 3.13.2.final.0
2025-03-16 13:23:33.461 [info] [Info  - 1:23:33 PM] (8392) Found 1 source file
2025-03-16 13:23:33.851 [info] [Info  - 1:23:33 PM] (8392) Background analysis(1) root directory: file:///c%3A/Users/Charl/.vscode/extensions/ms-python.vscode-pylance-2025.3.2/dist
2025-03-16 13:23:33.854 [info] [Info  - 1:23:33 PM] (8392) Background analysis(1) started
2025-03-16 13:23:34.026 [info] [Info  - 1:23:34 PM] (8392) Indexer background runner(2) root directory: file:///c%3A/Users/Charl/.vscode/extensions/ms-python.vscode-pylance-2025.3.2/dist (index)
2025-03-16 13:23:34.027 [info] [Info  - 1:23:34 PM] (8392) Indexing(2) started
2025-03-16 13:23:34.784 [info] [Info  - 1:23:34 PM] (8392) scanned(2) 11 files over 1 exec env
2025-03-16 13:23:34.927 [info] [Info  - 1:23:34 PM] (8392) indexed(2) 11 files over 1 exec env
2025-03-16 13:23:34.938 [info] [Info  - 1:23:34 PM] (8392) Indexing finished(2).
2025-03-16 13:23:40.310 [info] (Client) Pylance async client (2025.3.2) started with python extension (2025.2.0)
2025-03-16 13:23:40.983 [info] [Info  - 1:23:40 PM] (19900) Server root directory: file:///c%3A/Users/Charl/.vscode/extensions/ms-python.vscode-pylance-2025.3.2/dist
2025-03-16 13:23:40.984 [info] [Info  - 1:23:40 PM] (19900) Pylance language server 2025.3.2 (pyright version 1.1.396, commit 3e2236a7) starting
2025-03-16 13:23:40.991 [info] [Info  - 1:23:40 PM] (19900) Starting service instance "getya proyecto"
2025-03-16 13:23:41.077 [info] [Info  - 1:23:41 PM] (19900) Setting environmentName for service "getya proyecto": "3.13.2 (global)"
2025-03-16 13:23:41.077 [info] [Info  - 1:23:41 PM] (19900) Setting pythonPath for service "getya proyecto": "C:\Users\Charl\AppData\Local\Programs\Python\Python313\python.exe"
2025-03-16 13:23:41.078 [info] [Info  - 1:23:41 PM] (19900) No include entries specified; assuming c:\Users\Charl\Desktop\getya proyecto
2025-03-16 13:23:41.078 [info] [Info  - 1:23:41 PM] (19900) Auto-excluding **/node_modules
2025-03-16 13:23:41.079 [info] [Info  - 1:23:41 PM] (19900) Auto-excluding **/__pycache__
2025-03-16 13:23:41.079 [info] [Info  - 1:23:41 PM] (19900) Auto-excluding **/.*
2025-03-16 13:23:41.136 [info] [Info  - 1:23:41 PM] (19900) Assuming Python version 3.13.2.final.0
2025-03-16 13:23:41.294 [info] [Info  - 1:23:41 PM] (19900) Found 1 source file
2025-03-16 13:23:41.661 [info] [Info  - 1:23:41 PM] (19900) Background analysis(1) root directory: file:///c%3A/Users/Charl/.vscode/extensions/ms-python.vscode-pylance-2025.3.2/dist
2025-03-16 13:23:41.663 [info] [Info  - 1:23:41 PM] (19900) Background analysis(1) started
2025-03-16 13:23:41.851 [info] [Info  - 1:23:41 PM] (19900) Indexer background runner(2) root directory: file:///c%3A/Users/Charl/.vscode/extensions/ms-python.vscode-pylance-2025.3.2/dist (index)
2025-03-16 13:23:41.851 [info] [Info  - 1:23:41 PM] (19900) Indexing(2) started
2025-03-16 13:23:42.637 [info] [Info  - 1:23:42 PM] (19900) scanned(2) 11 files over 1 exec env
2025-03-16 13:23:42.773 [info] [Info  - 1:23:42 PM] (19900) indexed(2) 11 files over 1 exec env
2025-03-16 13:23:42.783 [info] [Info  - 1:23:42 PM] (19900) Indexing finished(2).
2025-03-16 13:23:46.565 [info] [Info  - 1:23:46 PM] Server process exited successfully
2025-03-16 13:23:47.089 [info] (Client) Pylance async client (2025.3.2) started with python extension (2025.2.0)
2025-03-16 13:23:47.623 [info] [Info  - 1:23:47 PM] (10884) Server root directory: file:///c%3A/Users/Charl/.vscode/extensions/ms-python.vscode-pylance-2025.3.2/dist
2025-03-16 13:23:47.625 [info] [Info  - 1:23:47 PM] (10884) Pylance language server 2025.3.2 (pyright version 1.1.396, commit 3e2236a7) starting
2025-03-16 13:23:47.630 [info] [Info  - 1:23:47 PM] (10884) Starting service instance "getya proyecto"
2025-03-16 13:23:47.656 [info] [Info  - 1:23:47 PM] (10884) Setting environmentName for service "getya proyecto": "3.13.2 (global)"
2025-03-16 13:23:47.656 [info] [Info  - 1:23:47 PM] (10884) Setting pythonPath for service "getya proyecto": "C:\Users\Charl\AppData\Local\Programs\Python\Python313\python.exe"
2025-03-16 13:23:47.657 [info] [Info  - 1:23:47 PM] (10884) No include entries specified; assuming c:\Users\Charl\Desktop\getya proyecto
2025-03-16 13:23:47.657 [info] [Info  - 1:23:47 PM] (10884) Auto-excluding **/node_modules
2025-03-16 13:23:47.657 [info] [Info  - 1:23:47 PM] (10884) Auto-excluding **/__pycache__
2025-03-16 13:23:47.657 [info] [Info  - 1:23:47 PM] (10884) Auto-excluding **/.*
2025-03-16 13:23:47.710 [info] [Info  - 1:23:47 PM] (10884) Assuming Python version 3.13.2.final.0
2025-03-16 13:23:47.859 [info] [Info  - 1:23:47 PM] (10884) Found 1 source file
2025-03-16 13:23:48.232 [info] [Info  - 1:23:48 PM] (10884) Background analysis(1) root directory: file:///c%3A/Users/Charl/.vscode/extensions/ms-python.vscode-pylance-2025.3.2/dist
2025-03-16 13:23:48.234 [info] [Info  - 1:23:48 PM] (10884) Background analysis(1) started
2025-03-16 13:23:48.388 [info] [Info  - 1:23:48 PM] (10884) Indexer background runner(2) root directory: file:///c%3A/Users/Charl/.vscode/extensions/ms-python.vscode-pylance-2025.3.2/dist (index)
2025-03-16 13:23:48.389 [info] [Info  - 1:23:48 PM] (10884) Indexing(2) started
2025-03-16 13:23:49.183 [info] [Info  - 1:23:49 PM] (10884) scanned(2) 11 files over 1 exec env
2025-03-16 13:23:49.328 [info] [Info  - 1:23:49 PM] (10884) indexed(2) 11 files over 1 exec env
2025-03-16 13:23:49.339 [info] [Info  - 1:23:49 PM] (10884) Indexing finished(2).
2025-03-16 13:24:03.735 [info] [Info  - 1:24:03 PM] (10884) Starting service instance "<default>"
2025-03-16 13:24:03.769 [info] [Info  - 1:24:03 PM] (10884) Setting environmentName for service "<default>": "3.13.2 (global)"
2025-03-16 13:24:03.770 [info] [Info  - 1:24:03 PM] (10884) Setting pythonPath for service "<default>": "c:\Users\Charl\AppData\Local\Programs\Python\Python313\python.exe"
2025-03-16 13:24:03.770 [info] [Info  - 1:24:03 PM] (10884) No include entries specified; assuming \<default workspace root>
2025-03-16 13:24:03.770 [info] [Info  - 1:24:03 PM] (10884) Auto-excluding **/node_modules
2025-03-16 13:24:03.770 [info] [Info  - 1:24:03 PM] (10884) Auto-excluding **/__pycache__
2025-03-16 13:24:03.770 [info] [Info  - 1:24:03 PM] (10884) Auto-excluding **/.*
2025-03-16 13:24:03.824 [info] [Info  - 1:24:03 PM] (10884) Assuming Python version 3.13.2.final.0
2025-03-16 13:24:03.954 [info] [Error - 1:24:03 PM] (10884) File or directory "\<default workspace root>" does not exist.
2025-03-16 13:24:03.954 [info] [Info  - 1:24:03 PM] (10884) No source files found.
2025-03-16 13:24:04.370 [info] [Info  - 1:24:04 PM] (10884) Background analysis(3) root directory: file:///c%3A/Users/Charl/.vscode/extensions/ms-python.vscode-pylance-2025.3.2/dist
2025-03-16 13:24:04.372 [info] [Info  - 1:24:04 PM] (10884) Background analysis(3) started
2025-03-16 13:26:07.761 [info] [Info  - 1:26:07 PM] (10884) No source files found.
2025-03-16 13:30:09.572 [info] [Info  - 1:30:09 PM] (10884) Setting environmentName for service "getya proyecto": "3.13.2 (global)"
2025-03-16 13:30:09.572 [info] [Info  - 1:30:09 PM] (10884) Setting pythonPath for service "getya proyecto": "C:\Users\Charl\AppData\Local\Programs\Python\Python313\python.exe"
2025-03-16 13:30:09.573 [info] [Info  - 1:30:09 PM] (10884) No include entries specified; assuming c:\Users\Charl\Desktop\getya proyecto
2025-03-16 13:30:09.573 [info] [Info  - 1:30:09 PM] (10884) Auto-excluding **/node_modules
2025-03-16 13:30:09.574 [info] [Info  - 1:30:09 PM] (10884) Auto-excluding **/__pycache__
2025-03-16 13:30:09.574 [info] [Info  - 1:30:09 PM] (10884) Auto-excluding **/.*
2025-03-16 13:30:09.628 [info] [Info  - 1:30:09 PM] (10884) Assuming Python version 3.13.2.final.0
2025-03-16 13:30:09.760 [info] [Info  - 1:30:09 PM] (10884) No source files found.
2025-03-16 13:30:09.764 [info] [Info  - 1:30:09 PM] (10884) Setting environmentName for service "<default>": "3.13.2 (global)"
2025-03-16 13:30:09.765 [info] [Info  - 1:30:09 PM] (10884) Setting pythonPath for service "<default>": "c:\Users\Charl\AppData\Local\Programs\Python\Python313\python.exe"
2025-03-16 13:30:09.765 [info] [Info  - 1:30:09 PM] (10884) No include entries specified; assuming \<default workspace root>
2025-03-16 13:30:09.765 [info] [Info  - 1:30:09 PM] (10884) Auto-excluding **/node_modules
2025-03-16 13:30:09.765 [info] [Info  - 1:30:09 PM] (10884) Auto-excluding **/__pycache__
2025-03-16 13:30:09.765 [info] [Info  - 1:30:09 PM] (10884) Auto-excluding **/.*
2025-03-16 13:30:09.819 [info] [Info  - 1:30:09 PM] (10884) Assuming Python version 3.13.2.final.0
2025-03-16 13:30:09.940 [info] [Error - 1:30:09 PM] (10884) File or directory "\<default workspace root>" does not exist.
2025-03-16 13:30:09.940 [info] [Info  - 1:30:09 PM] (10884) No source files found.
2025-03-16 13:30:14.986 [info] [Info  - 1:30:14 PM] (10884) Setting environmentName for service "getya proyecto": "3.13.2 (global)"
2025-03-16 13:30:14.986 [info] [Info  - 1:30:14 PM] (10884) Setting pythonPath for service "getya proyecto": "C:\Users\Charl\AppData\Local\Programs\Python\Python313\python.exe"
2025-03-16 13:30:14.986 [info] [Info  - 1:30:14 PM] (10884) No include entries specified; assuming c:\Users\Charl\Desktop\getya proyecto
2025-03-16 13:30:14.986 [info] [Info  - 1:30:14 PM] (10884) Auto-excluding **/node_modules
2025-03-16 13:30:14.986 [info] [Info  - 1:30:14 PM] (10884) Auto-excluding **/__pycache__
2025-03-16 13:30:14.986 [info] [Info  - 1:30:14 PM] (10884) Auto-excluding **/.*
2025-03-16 13:30:15.040 [info] [Info  - 1:30:15 PM] (10884) Assuming Python version 3.13.2.final.0
2025-03-16 13:30:15.170 [info] [Info  - 1:30:15 PM] (10884) No source files found.
2025-03-16 13:30:15.175 [info] [Info  - 1:30:15 PM] (10884) Setting environmentName for service "<default>": "3.13.2 (global)"
2025-03-16 13:30:15.175 [info] [Info  - 1:30:15 PM] (10884) Setting pythonPath for service "<default>": "c:\Users\Charl\AppData\Local\Programs\Python\Python313\python.exe"
2025-03-16 13:30:15.175 [info] [Info  - 1:30:15 PM] (10884) No include entries specified; assuming \<default workspace root>
2025-03-16 13:30:15.175 [info] [Info  - 1:30:15 PM] (10884) Auto-excluding **/node_modules
2025-03-16 13:30:15.175 [info] [Info  - 1:30:15 PM] (10884) Auto-excluding **/__pycache__
2025-03-16 13:30:15.176 [info] [Info  - 1:30:15 PM] (10884) Auto-excluding **/.*
2025-03-16 13:30:15.236 [info] [Info  - 1:30:15 PM] (10884) Assuming Python version 3.13.2.final.0
2025-03-16 13:30:15.369 [info] [Error - 1:30:15 PM] (10884) File or directory "\<default workspace root>" does not exist.
2025-03-16 13:30:15.369 [info] [Info  - 1:30:15 PM] (10884) No source files found.
2025-03-16 13:30:34.902 [info] [Info  - 1:30:34 PM] (10884) Setting environmentName for service "getya proyecto": "3.13.2 (global)"
2025-03-16 13:30:34.902 [info] [Info  - 1:30:34 PM] (10884) Setting pythonPath for service "getya proyecto": "C:\Users\Charl\AppData\Local\Programs\Python\Python313\python.exe"
2025-03-16 13:30:34.902 [info] [Info  - 1:30:34 PM] (10884) No include entries specified; assuming c:\Users\Charl\Desktop\getya proyecto
2025-03-16 13:30:34.902 [info] [Info  - 1:30:34 PM] (10884) Auto-excluding **/node_modules
2025-03-16 13:30:34.902 [info] [Info  - 1:30:34 PM] (10884) Auto-excluding **/__pycache__
2025-03-16 13:30:34.902 [info] [Info  - 1:30:34 PM] (10884) Auto-excluding **/.*
2025-03-16 13:30:34.952 [info] [Info  - 1:30:34 PM] (10884) Assuming Python version 3.13.2.final.0
2025-03-16 13:30:35.076 [info] [Info  - 1:30:35 PM] (10884) No source files found.
2025-03-16 13:30:35.080 [info] [Info  - 1:30:35 PM] (10884) Setting environmentName for service "<default>": "3.13.2 (global)"
2025-03-16 13:30:35.080 [info] [Info  - 1:30:35 PM] (10884) Setting pythonPath for service "<default>": "c:\Users\Charl\AppData\Local\Programs\Python\Python313\python.exe"
2025-03-16 13:30:35.081 [info] [Info  - 1:30:35 PM] (10884) No include entries specified; assuming \<default workspace root>
2025-03-16 13:30:35.081 [info] [Info  - 1:30:35 PM] (10884) Auto-excluding **/node_modules
2025-03-16 13:30:35.081 [info] [Info  - 1:30:35 PM] (10884) Auto-excluding **/__pycache__
2025-03-16 13:30:35.081 [info] [Info  - 1:30:35 PM] (10884) Auto-excluding **/.*
2025-03-16 13:30:35.138 [info] [Info  - 1:30:35 PM] (10884) Assuming Python version 3.13.2.final.0
2025-03-16 13:30:35.270 [info] [Error - 1:30:35 PM] (10884) File or directory "\<default workspace root>" does not exist.
2025-03-16 13:30:35.270 [info] [Info  - 1:30:35 PM] (10884) No source files found.
2025-03-16 13:31:03.903 [info] [Info  - 1:31:03 PM] Server process exited successfully
2025-03-16 13:31:04.467 [info] (Client) Pylance async client (2025.3.2) started with python extension (2025.2.0)
2025-03-16 13:31:05.004 [info] [Info  - 1:31:05 PM] (10320) Server root directory: file:///c%3A/Users/Charl/.vscode/extensions/ms-python.vscode-pylance-2025.3.2/dist
2025-03-16 13:31:05.006 [info] [Info  - 1:31:05 PM] (10320) Pylance language server 2025.3.2 (pyright version 1.1.396, commit 3e2236a7) starting
2025-03-16 13:31:05.011 [info] [Info  - 1:31:05 PM] (10320) Starting service instance "getya proyecto"
2025-03-16 13:31:05.036 [info] [Info  - 1:31:05 PM] (10320) Setting environmentName for service "getya proyecto": "3.13.2 (global)"
2025-03-16 13:31:05.037 [info] [Info  - 1:31:05 PM] (10320) Setting pythonPath for service "getya proyecto": "C:\Users\Charl\AppData\Local\Programs\Python\Python313\python.exe"
2025-03-16 13:31:05.037 [info] [Info  - 1:31:05 PM] (10320) No include entries specified; assuming c:\Users\Charl\Desktop\getya proyecto
2025-03-16 13:31:05.038 [info] [Info  - 1:31:05 PM] (10320) Auto-excluding **/node_modules
2025-03-16 13:31:05.038 [info] [Info  - 1:31:05 PM] (10320) Auto-excluding **/__pycache__
2025-03-16 13:31:05.039 [info] [Info  - 1:31:05 PM] (10320) Auto-excluding **/.*
2025-03-16 13:31:05.092 [info] [Info  - 1:31:05 PM] (10320) Assuming Python version 3.13.2.final.0
2025-03-16 13:31:05.239 [info] [Info  - 1:31:05 PM] (10320) No source files found.
2025-03-16 13:31:05.578 [info] [Info  - 1:31:05 PM] (10320) Background analysis(1) root directory: file:///c%3A/Users/Charl/.vscode/extensions/ms-python.vscode-pylance-2025.3.2/dist
2025-03-16 13:31:05.581 [info] [Info  - 1:31:05 PM] (10320) Background analysis(1) started
2025-03-16 13:32:12.440 [info] [Info  - 1:32:12 PM] Server process exited successfully
2025-03-16 13:32:12.946 [info] (Client) Pylance async client (2025.3.2) started with python extension (2025.2.0)
2025-03-16 13:32:13.492 [info] [Info  - 1:32:13 PM] (5592) Server root directory: file:///c%3A/Users/Charl/.vscode/extensions/ms-python.vscode-pylance-2025.3.2/dist
2025-03-16 13:32:13.493 [info] [Info  - 1:32:13 PM] (5592) Pylance language server 2025.3.2 (pyright version 1.1.396, commit 3e2236a7) starting
2025-03-16 13:32:13.498 [info] [Info  - 1:32:13 PM] (5592) Starting service instance "getya proyecto"
2025-03-16 13:32:13.524 [info] [Info  - 1:32:13 PM] (5592) Setting environmentName for service "getya proyecto": "3.13.2 (global)"
2025-03-16 13:32:13.524 [info] [Info  - 1:32:13 PM] (5592) Setting pythonPath for service "getya proyecto": "C:\Users\Charl\AppData\Local\Programs\Python\Python313\python.exe"
2025-03-16 13:32:13.525 [info] [Info  - 1:32:13 PM] (5592) No include entries specified; assuming c:\Users\Charl\Desktop\getya proyecto
2025-03-16 13:32:13.525 [info] [Info  - 1:32:13 PM] (5592) Auto-excluding **/node_modules
2025-03-16 13:32:13.525 [info] [Info  - 1:32:13 PM] (5592) Auto-excluding **/__pycache__
2025-03-16 13:32:13.525 [info] [Info  - 1:32:13 PM] (5592) Auto-excluding **/.*
2025-03-16 13:32:13.580 [info] [Info  - 1:32:13 PM] (5592) Assuming Python version 3.13.2.final.0
2025-03-16 13:32:13.727 [info] [Info  - 1:32:13 PM] (5592) No source files found.
2025-03-16 13:32:14.062 [info] [Info  - 1:32:14 PM] (5592) Background analysis(1) root directory: file:///c%3A/Users/Charl/.vscode/extensions/ms-python.vscode-pylance-2025.3.2/dist
2025-03-16 13:32:14.065 [info] [Info  - 1:32:14 PM] (5592) Background analysis(1) started
2025-03-16 13:33:02.702 [info] (Client) Pylance async client (2025.3.2) started with python extension (2025.2.0)
2025-03-16 13:33:03.336 [info] [Info  - 1:33:03 PM] (13148) Server root directory: file:///c%3A/Users/Charl/.vscode/extensions/ms-python.vscode-pylance-2025.3.2/dist
2025-03-16 13:33:03.338 [info] [Info  - 1:33:03 PM] (13148) Pylance language server 2025.3.2 (pyright version 1.1.396, commit 3e2236a7) starting
2025-03-16 13:33:03.343 [info] [Info  - 1:33:03 PM] (13148) Starting service instance "getya proyecto"
2025-03-16 13:33:03.421 [info] [Info  - 1:33:03 PM] (13148) Setting environmentName for service "getya proyecto": "3.13.2 (global)"
2025-03-16 13:33:03.421 [info] [Info  - 1:33:03 PM] (13148) Setting pythonPath for service "getya proyecto": "C:\Users\Charl\AppData\Local\Programs\Python\Python313\python.exe"
2025-03-16 13:33:03.421 [info] [Info  - 1:33:03 PM] (13148) No include entries specified; assuming c:\Users\Charl\Desktop\getya proyecto
2025-03-16 13:33:03.422 [info] [Info  - 1:33:03 PM] (13148) Auto-excluding **/node_modules
2025-03-16 13:33:03.422 [info] [Info  - 1:33:03 PM] (13148) Auto-excluding **/__pycache__
2025-03-16 13:33:03.422 [info] [Info  - 1:33:03 PM] (13148) Auto-excluding **/.*
2025-03-16 13:33:03.483 [info] [Info  - 1:33:03 PM] (13148) Assuming Python version 3.13.2.final.0
2025-03-16 13:33:03.641 [info] [Info  - 1:33:03 PM] (13148) No source files found.
2025-03-16 13:33:04.004 [info] [Info  - 1:33:04 PM] (13148) Background analysis(1) root directory: file:///c%3A/Users/Charl/.vscode/extensions/ms-python.vscode-pylance-2025.3.2/dist
2025-03-16 13:33:04.006 [info] [Info  - 1:33:04 PM] (13148) Background analysis(1) started
2025-03-16 13:33:13.194 [info] [Info  - 1:33:13 PM] (13148) Setting environmentName for service "getya proyecto": "3.13.2 (global)"
2025-03-16 13:33:13.194 [info] [Info  - 1:33:13 PM] (13148) Setting pythonPath for service "getya proyecto": "C:\Users\Charl\AppData\Local\Programs\Python\Python313\python.exe"
2025-03-16 13:33:13.194 [info] [Info  - 1:33:13 PM] (13148) No include entries specified; assuming c:\Users\Charl\Desktop\getya proyecto
2025-03-16 13:33:13.195 [info] [Info  - 1:33:13 PM] (13148) Auto-excluding **/node_modules
2025-03-16 13:33:13.195 [info] [Info  - 1:33:13 PM] (13148) Auto-excluding **/__pycache__
2025-03-16 13:33:13.195 [info] [Info  - 1:33:13 PM] (13148) Auto-excluding **/.*
2025-03-16 13:33:13.243 [info] [Info  - 1:33:13 PM] (13148) Assuming Python version 3.13.2.final.0
2025-03-16 13:33:13.363 [info] [Info  - 1:33:13 PM] (13148) No source files found.
2025-03-16 13:37:50.984 [info] [Info  - 1:37:50 PM] Server process exited successfully
2025-03-16 13:37:51.584 [info] (Client) Pylance async client (2025.3.2) started with python extension (2025.2.0)
2025-03-16 13:37:52.164 [info] [Info  - 1:37:52 PM] (6796) Server root directory: file:///c%3A/Users/Charl/.vscode/extensions/ms-python.vscode-pylance-2025.3.2/dist
2025-03-16 13:37:52.166 [info] [Info  - 1:37:52 PM] (6796) Pylance language server 2025.3.2 (pyright version 1.1.396, commit 3e2236a7) starting
2025-03-16 13:37:52.170 [info] [Info  - 1:37:52 PM] (6796) Starting service instance "getya proyecto"
2025-03-16 13:37:52.196 [info] [Info  - 1:37:52 PM] (6796) Setting environmentName for service "getya proyecto": "3.13.2 (global)"
2025-03-16 13:37:52.197 [info] [Info  - 1:37:52 PM] (6796) Setting pythonPath for service "getya proyecto": "C:\Users\Charl\AppData\Local\Programs\Python\Python313\python.exe"
2025-03-16 13:37:52.197 [info] [Info  - 1:37:52 PM] (6796) No include entries specified; assuming c:\Users\Charl\Desktop\getya proyecto
2025-03-16 13:37:52.198 [info] [Info  - 1:37:52 PM] (6796) Auto-excluding **/node_modules
2025-03-16 13:37:52.198 [info] [Info  - 1:37:52 PM] (6796) Auto-excluding **/__pycache__
2025-03-16 13:37:52.198 [info] [Info  - 1:37:52 PM] (6796) Auto-excluding **/.*
2025-03-16 13:37:52.251 [info] [Info  - 1:37:52 PM] (6796) Assuming Python version 3.13.2.final.0
2025-03-16 13:37:52.393 [info] [Info  - 1:37:52 PM] (6796) No source files found.
2025-03-16 13:37:52.711 [info] [Info  - 1:37:52 PM] (6796) Background analysis(1) root directory: file:///c%3A/Users/Charl/.vscode/extensions/ms-python.vscode-pylance-2025.3.2/dist
2025-03-16 13:37:52.713 [info] [Info  - 1:37:52 PM] (6796) Background analysis(1) started
2025-03-16 13:39:42.098 [info] [Info  - 1:39:42 PM] Server process exited successfully
2025-03-16 13:39:42.679 [info] (Client) Pylance async client (2025.3.2) started with python extension (2025.2.0)
2025-03-16 13:39:43.199 [info] [Info  - 1:39:43 PM] (8896) Server root directory: file:///c%3A/Users/Charl/.vscode/extensions/ms-python.vscode-pylance-2025.3.2/dist
2025-03-16 13:39:43.200 [info] [Info  - 1:39:43 PM] (8896) Pylance language server 2025.3.2 (pyright version 1.1.396, commit 3e2236a7) starting
2025-03-16 13:39:43.205 [info] [Info  - 1:39:43 PM] (8896) Starting service instance "getya proyecto"
2025-03-16 13:39:43.232 [info] [Info  - 1:39:43 PM] (8896) Setting environmentName for service "getya proyecto": "3.13.2 (global)"
2025-03-16 13:39:43.232 [info] [Info  - 1:39:43 PM] (8896) Setting pythonPath for service "getya proyecto": "C:\Users\Charl\AppData\Local\Programs\Python\Python313\python.exe"
2025-03-16 13:39:43.232 [info] [Info  - 1:39:43 PM] (8896) No include entries specified; assuming c:\Users\Charl\Desktop\getya proyecto
2025-03-16 13:39:43.233 [info] [Info  - 1:39:43 PM] (8896) Auto-excluding **/node_modules
2025-03-16 13:39:43.233 [info] [Info  - 1:39:43 PM] (8896) Auto-excluding **/__pycache__
2025-03-16 13:39:43.233 [info] [Info  - 1:39:43 PM] (8896) Auto-excluding **/.*
2025-03-16 13:39:43.288 [info] [Info  - 1:39:43 PM] (8896) Assuming Python version 3.13.2.final.0
2025-03-16 13:39:43.445 [info] [Info  - 1:39:43 PM] (8896) No source files found.
2025-03-16 13:39:43.778 [info] [Info  - 1:39:43 PM] (8896) Background analysis(1) root directory: file:///c%3A/Users/Charl/.vscode/extensions/ms-python.vscode-pylance-2025.3.2/dist
2025-03-16 13:39:43.780 [info] [Info  - 1:39:43 PM] (8896) Background analysis(1) started
2025-03-16 13:39:49.983 [info] [Info  - 1:39:49 PM] (8896) Starting service instance "<default>"
2025-03-16 13:39:50.005 [info] [Info  - 1:39:50 PM] (8896) Setting environmentName for service "<default>": "3.13.2 (global)"
2025-03-16 13:39:50.005 [info] [Info  - 1:39:50 PM] (8896) Setting pythonPath for service "<default>": "c:\Users\Charl\AppData\Local\Programs\Python\Python313\python.exe"
2025-03-16 13:39:50.006 [info] [Info  - 1:39:50 PM] (8896) No include entries specified; assuming \<default workspace root>
2025-03-16 13:39:50.006 [info] [Info  - 1:39:50 PM] (8896) Auto-excluding **/node_modules
2025-03-16 13:39:50.006 [info] [Info  - 1:39:50 PM] (8896) Auto-excluding **/__pycache__
2025-03-16 13:39:50.006 [info] [Info  - 1:39:50 PM] (8896) Auto-excluding **/.*
2025-03-16 13:39:50.105 [info] [Info  - 1:39:50 PM] (8896) Assuming Python version 3.13.2.final.0
2025-03-16 13:39:50.286 [info] [Error - 1:39:50 PM] (8896) File or directory "\<default workspace root>" does not exist.
2025-03-16 13:39:50.287 [info] [Info  - 1:39:50 PM] (8896) No source files found.
2025-03-16 13:39:50.702 [info] [Info  - 1:39:50 PM] (8896) Indexer background runner(2) root directory: file:///c%3A/Users/Charl/.vscode/extensions/ms-python.vscode-pylance-2025.3.2/dist (index)
2025-03-16 13:39:50.702 [info] [Info  - 1:39:50 PM] (8896) Indexing(2) started
2025-03-16 13:39:50.727 [info] [Info  - 1:39:50 PM] (8896) Found 1 source file
2025-03-16 13:39:50.783 [info] [Info  - 1:39:50 PM] (8896) Background analysis(3) root directory: file:///c%3A/Users/Charl/.vscode/extensions/ms-python.vscode-pylance-2025.3.2/dist
2025-03-16 13:39:50.786 [info] [Info  - 1:39:50 PM] (8896) Background analysis(3) started
2025-03-16 13:39:51.590 [info] [Info  - 1:39:51 PM] (8896) scanned(2) 11 files over 1 exec env
2025-03-16 13:39:51.733 [info] [Info  - 1:39:51 PM] (8896) indexed(2) 11 files over 1 exec env
2025-03-16 13:39:51.745 [info] [Info  - 1:39:51 PM] (8896) Indexing finished(2).
2025-03-16 14:56:36.599 [info] [Info  - 2:56:36 PM] (8896) Found 1 source file
